
services:
  go-app:
    container_name: go-app
    image: project-api-go
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/go/src/app
    working_dir : /go/src/app
    command: air    
    depends_on:
      - go_db  
  go_db:
    container_name: go_db
    image: postgres:12
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: {}